vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    products:
      uri_prefix: /images/restaurants
      upload_destination: "%kernel.project_dir%/public/images/restaurants"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
